package src;

public enum TokenType {

    BEGIN, LPAREN ,RPAPREN, PLUS, MINUS, ASTERISK, SLASH, ASSIGN, SEMICOLON, READ, WRITE, END, IF, THEN, ELSE, ENDIF, WHILE, ENDWH, ID, NUMBER, EXPRESSION, EOF, EPS
}
